### ISSUE TITLE
Initial prototype

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#1]
The initial prototype of this will involve a YAML file that defines multiple screenshots to be taken, and a GitHub Actions workflow that takes those screenshots.

**Comment by simonw** [comment]
Asked for help on Twitter: https://twitter.com/simonw/status/1501335967642255365

**Comment by rubys** [comment]
Add a package.json file.  Publish the result to npm.  I suggest using a scope: https://docs.npmjs.com/cli/v8/using-npm/scope

An example of a small tool I wrote for a colleague to use: https://github.com/rubys/acah

**Comment by fabianMendez** [comment]
I am not sure I understand what you are trying to do, but what about this?:

```js
// script.js
const { chromium } = require('playwright');

(async () => {
	const browser = await chromium.launch()
	try {
		const page = await browser.newPage()
		await page.goto('https://simonwillison.net/')
		await page.locator('#bighead').screenshot({ path: 'bighead.png' })
	} finally {
		await browser.close()
	}
})()
```

```shell
export NODE_PATH=$(npm root --quiet -g) # https://stackoverflow.com/a/7971439
cat script.js | node --
```

**Comment by simonw** [comment]
I'm using Python Playwright now: https://github.com/simonw/shot-scraper/blob/63a0c2dfdde841e835cb73329c1a97b3297b765b/shot_scraper/cli.py#L42-L44

**Comment by simonw** [comment]
> Add a package.json file. Publish the result to npm. I suggest using a scope: https://docs.npmjs.com/cli/v8/using-npm/scope
> 
> An example of a small tool I wrote for a colleague to use: https://github.com/rubys/acah

Yeah, I agree - that would be the way to go if I was sticking with JavaScript Playwright. But it turns out Python Playwright works great for this project!

**Comment by simonw** [comment]
Continued work is happening in other issues now.
