### ISSUE TITLE
`--silent` option that allows for silencing echo outputs

### ISSUE THREAD

**Issue by palewire** [simonw/shot-scraper#107]
It would be nice to be able to run this command in "silent" mode somehow so that it wouldn't always log out to the stdout via the click echo function.

**Comment by simonw** [comment]
I'll do `--silent` for consistency with `sqlite-utils`: https://sqlite-utils.datasette.io/en/stable/cli-reference.html

**Comment by simonw** [comment]
I added it to the `shot-scraper shot`, `pdf` and `html` commands.

**Comment by simonw** [comment]
And the `shot-scraper multi` command too.
