### ISSUE TITLE
interactive mode doesn't respect viewport size for initial window

### ISSUE THREAD

**Issue by mhalle** [simonw/shot-scraper#127]
The `width` and `height` parameters for setting viewport size don't set the initial window size in interactive mode (though they are later used to set the viewport before the shot).

This fact makes interactive mode less useful because the playwright browser doesn't seem responsive to interactive window resizing. The initial size of the window is thus important.

Seems like calling `page.set_viewport_size()` after the interactive window is launched should work.

**Comment by simonw** [comment]
Fixed in:
- https://github.com/simonw/shot-scraper/pull/128

**Comment by simonw** [comment]
Before this fix:

```bash
shot-scraper https://simonwillison.net/ --interactive -h 700 -w 300
```
The interactive window ignored those options:

![CleanShot 2024-02-05 at 14 41 00@2x](https://github.com/simonw/shot-scraper/assets/9599/d0cb8780-3b5e-4c2d-ac80-2725b604b005)

After this fix:

![CleanShot 2024-02-05 at 14 42 22@2x](https://github.com/simonw/shot-scraper/assets/9599/d11c57fa-bd03-46e2-9cc1-06337c57a6ed)
