### ISSUE TITLE
Interactive automated browsing? (GPT-4V autopilot, simple scripting, etc)

### ISSUE THREAD

**Issue by walking-octopus** [simonw/shot-scraper#131]
I wonder if adding some mechanisms for keeping a session alive and using the CLI to send commands to it can help automate simple actions or hack together entire agents.

Say I want to create a script to auto-order N of item X. Or maybe open a session, start a chat with GPT-4, ask it a question, and have it use that headless browser to take a screenshot, annotate clickable parts with IDs, send back the screenshot and have it choose the interaction, etc, until it got the information it wanted to continue the chat with the user.

I don't know if it's a little beyond the scope of the project, but I think it can definitely be neat.

**Comment by nmstoker** [comment]
Wouldn't this be better done directly with [Playwright](https://playwright.dev/) which underlies shot-scraper?

**Comment by walking-octopus** [comment]
Yes, revisiting this issue, I do see it is most definitely not in the spirit of doing one thing well... I'll close it now.
