### ISSUE TITLE
Proposal: Add an option to make device scale factor flexible, in addition to the existing --retina argument

### ISSUE THREAD

**Issue by nielthiart** [simonw/shot-scraper#136]
The `--retina` argument is convenient to set a device scale factor of `2`, but for my use case I needed a variety of scale factors to match other displays.

Ref: #133

For example, Google Pixel 6 has a scale factor of `2.625`. Some devices go up to `4`.

My proposal is to add an additional argument, `--scale-factor`, that takes a float as argument, and is `None` by default.

To avoid confusion when using `--retina` and `--scale-factor` simultaneously, we could treat them as mutually exclusive and raise a helpful error. We can also check that the scale factor is positive.

A reusable function that validates and normalises the device scale factor provides the opportunity to validate other scale-factor-altering arguments in the future, such as the `--device` argument proposed in #129.

**Comment by simonw** [comment]
From a successful GitHub Actions run:

simonwillison-retina:

![simonwillison-retina](https://github.com/simonw/shot-scraper/assets/9599/373ef57d-f4aa-4a64-8ce6-334b14b17dea)

simonwillison-scale-factor-pixel-six:

![simonwillison-scale-factor-pixel-six](https://github.com/simonw/shot-scraper/assets/9599/c0d1b09a-0a73-424a-986f-2bae0991ef87)

https://github.com/simonw/shot-scraper/blob/b478542724d5768214d988caf7f755548f4d1d15/tests/run_examples.sh#L164-L169
