### ISSUE TITLE
Proposal: Add an option to pass custom browser arguments to Playwright when launching the browser

### ISSUE THREAD

**Issue by nielthiart** [simonw/shot-scraper#137]
I had the need to pass command line arguments to Playwright when launching a browser.

Chromium has a long [List of Chromium Command Line Switches](https://peter.sh/experiments/chromium-command-line-switches/) that users might find useful.

## Why I use browser arguments: font render hinting

Font rendering in headless chrome is inconsistent between different platforms. When testing on a mac, font rendering is good, but on GitHub's action runners (Linux) the kerning is off, which affects line lengths. Some fonts at smaller sizes also appear a few pixels too high or low.

One solution to fix this, is to pass the `--font-render-hinting=none` argument when calling `chromium.launch()`.

This solution comes up when users ask for help with font rendering in headless chrome, puppeteer, etc.

- https://github.com/puppeteer/puppeteer/issues/2410
- [Try to fix fonts rendering issues (bad kerning)](https://gerrit.wikimedia.org/r/c/mediawiki/services/chromium-render/+/442735)
- [How to fix Puppeteer font issues](https://www.browserless.io/blog/2020/09/30/puppeteer-print/)
- [Font hinting on Wikipedia](https://en.wikipedia.org/wiki/Font_hinting)

## Examples

Here's an example of a page captured in a GitHub action with and without font render hinting:

### Default font render hinting

```bash
shot-scraper "https://www.bellingcat.com/resources/2016/12/06/vacuuming-image-metadata-wayback-machine/" \
  -w 1200 -h 800 \
  -o examples/1-bellingcat-default.png
```

![1-bellingcat-default](https://github.com/simonw/shot-scraper/assets/154435/7a1061aa-9693-41f0-b34d-f471ad74470a)

The kerning is incorrect on small font sizes and lines wrap earlier.

### With font-render-hinting=none

```bash
shot-scraper "https://www.bellingcat.com/resources/2016/12/06/vacuuming-image-metadata-wayback-machine/" \
  -w 1200 -h 800 \
  -o examples/2-bellingcat-font-render-hinting-none.png \
  --browser-args "--font-render-hinting=none"
```

![2-bellingcat-font-render-hinting-none](https://github.com/simonw/shot-scraper/assets/154435/4f1dfc85-2755-4f79-a4b6-721439dd46cd)

The kerning looks much better here.

## Alternative solution: Unrelated to browser arguments

As a workaround, we can achieve similar font rendering results by using CSS to add ` text-rendering: geometricPrecision` to all elements:

```bash
shot-scraper "https://www.bellingcat.com/resources/2016/12/06/vacuuming-image-metadata-wayback-machine/" \
  -w 1200 -h 800 \
  -o examples/3-bellingcat-default-geomp.png \
  --javascript "(document.head || document.documentElement).appendChild(Object.assign(document.createElement('style'), {textContent: '*, ::before, ::after { text-rendering: geometricPrecision !important; }'}));"
```

![3-bellingcat-default-geomp](https://github.com/simonw/shot-scraper/assets/154435/52118548-47af-45ad-9084-8b987f35bee2)

I'd prefer not to add CSS if we can launch the browser with an argument that fixes font rendering instead.

**Comment by simonw** [comment]
Thanks for this, it's a really neat (and cleanly implemented) new feature.

**Comment by simonw** [comment]
Documentation is here: https://shot-scraper.datasette.io/en/latest/screenshots.html#browser-arguments

**Comment by simonw** [comment]
My bad, I messed up my change in https://github.com/simonw/shot-scraper/commit/cc199c4e38b288acc8ec3c46bdbef255c1e4a103. Will fix that now.

**Comment by simonw** [comment]
Here are the examples files that were created by the last GitHub Action CI run:

font-hinting-default:

![font-hinting-default](https://github.com/simonw/shot-scraper/assets/9599/13f17211-2b1d-4a29-a8db-ddb5b2ccdff3)

font-hinting-none:

![font-hinting-none](https://github.com/simonw/shot-scraper/assets/9599/136491f4-9822-4618-af21-f6c7a04f560f)
