### ISSUE TITLE
Mechanism for handling sites with authentication

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#18]
Feature suggestion from https://writethedocs.slack.com/archives/C72NZ18FR/p1646878775398999?thread_ts=1646877544.991549&cid=C72NZ18FR

**Comment by simonw** [comment]
The simplest way to do this would be to support adding extra headers to requests - that way users could define cookies to be sent.

But... cookies are fickle. They expire, which means the YAML file would stop working. They're not particularly user-friendly either.

The much more exciting way to solve this would be the Playwright way - allow users to define a sequence of steps, e.g. "Go to /login, then enter this username and password in these fields, then submit the form, then go to /x and take a screenshot".

I don't think it would be feasible to support that as one-off command-line options, it would need to be YAML only.

But within the YAML format it could be feasible!

(CAPTCHAs and 2FA would block this approach entirely.)

**Comment by simonw** [comment]
There's something deviously tempting about defining a mini YAML language that automates the process of visiting a page, filling in a form, submitting it, visiting another, snapping a screenshot, injecting some JavaScript, snapping another screenshot of a page element, navigating somewhere else...

**Comment by ryancheley** [comment]
@simonw 
Based on your [tweet](https://twitter.com/simonw/status/1501771354521042945) here are two potential use cases I was thinking about:

1. Logging into a site where some sort of social authentication is performed (a la django-allauth using GitHub, or Twitter as an authentication App)
2. Logging into a site using OKTA (this would be more for a work thing where we use OKTA to log into internal and external sites). OKTA uses 2FA so I'm not sure how that could be implemented. 

The reason item 2 above would be more for enterprise-y sorts of access, and so from a purely OSS perspective, may fall outside of reasonableness (unless you got some Enterprise to sponsor you 😄), but item 1 I think would be more generally purpose.

**Comment by simonw** [comment]
OK, I think there may be a way to support 2FA / CAPTCHAs / etc.

I could add an option which pops open an actual browser interface and waits for a human being to use that interface to login to the system - solving CAPTCHAs, doing 2FA - whatever it takes.

Then, once they have signed in, `shot-scraper` could dump out the resulting cookies to disk and use them for subsequent operations.

If the cookies expire that's fine - it can show an error and tell the user they need to authenticate again.

This would be a bit complex to build, but not impossible... and it would unlock a LOT of value for people.

As someone on the Write the Docs Slack pointed out, "Almost every product I've documented has been a Saas site with authentication". So this matters.

**Comment by simonw** [comment]
Playwright has some very relevant documentation on this here: https://playwright.dev/python/docs/auth

**Comment by simonw** [comment]
I'm going to save the file with 0600 by default, like in https://github.com/simonw/google-drive-to-sqlite/commit/18143e99cd5c16ee02bc04c9054f4be00415bcf6

**Comment by simonw** [comment]
This prototype works! It opens the browser window, and then dumps out the resulting cookies as JSON when the user hits "enter":

```python
@cli.command()
@click.argument("url")
def auth(url):
    """
    Open browser so user can manually authenticate with the specified site,
    then save the resulting authentication context to a file.

    Usage:

        shot-scraper auth https://github.com/
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()
        page.goto(url)
        click.echo("Hit <enter> after you have signed in:")
        input()
        storage = context.storage_state()
        print(storage)
```

**Comment by simonw** [comment]
I'm not going to default to dumping to standard out because that feels unsafe. I'll let people specify `-` if they really do want that.

I think this command takes two required arguments: the URL and the file to write the resulting state to.

**Comment by simonw** [comment]
Just tried this out with my blog:
```
% shot-scraper auth https://simonwillison.net/admin/ auth.json
Hit <enter> after you have signed in:

% cat auth.json 
{
    "cookies": [
        {
            "sameSite": "Lax",
            "name": "csrftoken",
            "value": "OEYfJYoP...",
            "domain": "simonwillison.net",
            "path": "/",
            "expires": 1678563913.345368,
            "httpOnly": false,
            "secure": false
        },
        {
            "sameSite": "Lax",
            "name": "sessionid",
            "value": "...",
            "domain": ".simonwillison.net",
            "path": "/",
            "expires": 1648323913.345399,
            "httpOnly": true,
            "secure": true
        }
    ],
    "origins": []
}
```

**Comment by simonw** [comment]
That totally worked!

    shot-scraper shot https://simonwillison.net/admin/ -o logged-in.png -a auth.json --wait 1000

![logged-in](https://user-images.githubusercontent.com/9599/158032964-4a33f8aa-d432-4f3f-b6db-29eda0c02bf1.png)

**Comment by simonw** [comment]
The `auth` command could take the standard `--javascript` option.

It could also take a `--headless` option - which causes it to open the page in regular headless mode, execute that JavaScript and then close the page again.

This would allow you to automate logins on pages that support it:

    shot-scraper auth https://site.local/ auth.json --headless --javascript "
    document.getElementById('#username').value = 'username';
    document.getElementById('#password').value = 'password';
    document.forms[0].submit();
    "

**Comment by simonw** [comment]
Testing against https://datasette-auth-passwords-demo.datasette.io/

Ran this:

    shot-scraper auth https://datasette-auth-passwords-demo.datasette.io/-/login ds-auth.json                                                                   

So now:
```
% shot-scraper accessibility -a ds-auth.json https://datasette-auth-passwords-demo.datasette.io/
{
    "role": "WebArea",
    "name": "datasette-auth-passwords demo: _internal, public, private",
    "children": [
        {
            "role": "DisclosureTriangle",
            "name": "Menu"
```
Compare with:
```
% shot-scraper accessibility https://datasette-auth-passwords-demo.datasette.io/
{
    "role": "WebArea",
    "name": "datasette-auth-passwords demo: public",
    "children": [
        {
            "role": "heading",
            "name": "datasette-auth-passwords demo",
            "level": 1
        },
        {
            "role": "text",
            "name": "Sign in at"
        },
```

**Comment by simonw** [comment]
shot-scraper pdf -a ds-auth.json https://datasette-auth-passwords-demo.datasette.io/ --landscape -o l.pdf                                                   

![CleanShot 2022-03-12 at 12 13 36@2x](https://user-images.githubusercontent.com/9599/158033479-5acced47-81a9-41d6-82fd-8e0c9ff4cddc.png)
