### ISSUE TITLE
Support taking a shot that boxes multiple selectors

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#21]
This is a bit of an unconventional need, but I think it's worth exploring.

When taking screenshots for tutorials, I often want to grab an area of the screen that incorporates more than one element - where there's no convenient wrapper element that I can use to get the shot that I want.

Imagine if you could specify multiple selectors and get back a screenshot of the smallest area of the screen that incorporates all of those elements.

The implement would look at the founding box of all of those elements, generate a new box that wraps all of those, inject an absolutely positioned box of that size and take the screenshot of that area.

It could even optionally add some padding to that box before taking the shot.

**Comment by simonw** [comment]
Potential syntax:

    shot-scraper $URL \
      --selector h1 --selector h2 --padding 10

So if you pass multiple selectors it creates a box around them.

In YAML could support a `selectors` list:

```yaml
- url: ...
  selectors:
  - h1
  - h2
  padding: 10
```

**Comment by andrlik** [comment]
Was just about to file this same request!

**Comment by simonw** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect says:

> If you need the bounding rectangle relative to the top-left corner of the document, just add the current scrolling position to the top and left properties (these can be obtained using [window.scrollX](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX) and [window.scrollY](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY)) to get a bounding rectangle which is independent from the current scrolling position.

**Comment by simonw** [comment]
Here are the bounding rectangles for two elements on a page:
```
{
   "x": 16,
   "y": 181.60000610351562,
   "width": 799,
   "height": 30,
   "top": 181.60000610351562,
   "right": 815,
   "bottom": 211.60000610351562,
   "left": 16
}
{
   "x": 16,
   "y": 215.60000610351562,
   "width": 799,
   "height": 112.16665649414062,
   "top": 215.60000610351562,
   "right": 815,
   "bottom": 327.76666259765625,
   "left": 16
}
```

**Comment by simonw** [comment]
I think I need the min top and left and the max bottom and right.

**Comment by simonw** [comment]
OK, this function seems to work nicely:
```javascript
function addBoundingBox(els, padding) {
    // Add an absolutely positioned bounding box that wraps all elements
    padding = padding || 0;
    let minTop = 100000000;
    let minLeft = 100000000;
    let maxBottom = 0;
    let maxRight = 0;
    els.forEach(el => {
        let rect = el.getBoundingClientRect();
        if (rect.top < minTop) {
            minTop = rect.top;
        }
        if (rect.left < minLeft) {
            minLeft = rect.left;
        }
        if (rect.bottom > maxBottom) {
            maxBottom = rect.bottom;
        }
        if (rect.right > maxRight) {
            maxRight = rect.right;
        }
    });
    console.log({minTop, minLeft, maxBottom, maxRight});
    // Adjust them based on scroll position
    let top = minTop + window.scrollY;
    let bottom = maxBottom + window.scrollY;
    let left = minLeft + window.scrollX;
    let right = maxRight + window.scrollX;
    // Apply padding
    top = top - padding;
    bottom = bottom + padding;
    left = left - padding;
    right = right + padding;
    var div = document.createElement('div');
    div.style.position = 'absolute';
    div.style.outline = '2px dashed red';
    div.style.top = top + 'px';
    div.style.left = left + 'px';
    div.style.width = (right - left) + 'px';
    div.style.height = (bottom - top) + 'px';
    
    document.body.appendChild(div);
}
```
On https://congress-legislators.datasettes.com/legislators/legislators?bio_gender__exact=F
```javascript
addBoundingBox(document.querySelectorAll('form.filters,.suggested-facets'), 5)
```
<img width="826" alt="image" src="https://user-images.githubusercontent.com/9599/158031463-5a6d0f63-7bf7-4c0e-a73c-1b5b1f505350.png">

**Comment by simonw** [comment]
Got it working:

    shot-scraper https://simonwillison.net/ -s '#bighead' -o big.png -s .overband --padding 20

![big](https://user-images.githubusercontent.com/9599/158034335-5d834914-5a84-4353-b007-e0c6151bf122.png)
