### ISSUE TITLE
Allow taking an snapshot of a local file

### ISSUE THREAD

**Issue by pjamargh** [simonw/shot-scraper#35]
For an .html file stored locally I use `python -m http.server 80` and then `shot-scraper http://localhost/file` but it would be handy to be able to just point shot-scraper to the file directly.

**Comment by simonw** [comment]
I agree, this would definitely be useful.

**Comment by simonw** [comment]
Deleting this check:

https://github.com/simonw/shot-scraper/blob/773377e4d0422b46ff302717f553ae5018b667f6/shot_scraper/cli.py#L352-L355

And then running the following worked:

    shot-scraper file:/tmp/index.html

I had to provide both `file:/` and a full path to the file though.

So the actual implementation of that should probably notice when the user provides a URL that doesn't start with `http://` or `https://` AND is a file that exists on disk and, if so, do the work of turning that into a `file://full/path/to/filename.html`.

**Comment by pjamargh** [comment]
Thanks for the quick response!

Shot-scraper has been a great help for transforming complex epub ebooks into easier to display series of images. Thanks a lot for this tool!

**Comment by simonw** [comment]
I'm intrigued! Hadn't considered there might be epub applications.

**Comment by pjamargh** [comment]
They use XHTML. Some are simple (say some images and texts) totally ok to reflow, some are complex. On these last group you have some comics that have images but also transparent text on top so it is readable for accessibility, some others have images without the text and text on top with complex transformations (tilting and such). There are rarely displayed properly in a simple epub reader. I'm still testing but with a little fine fiddling shot-scraper is giving me exactly what I needed (rendering one HTML page into an image).

**Comment by simonw** [comment]
Tested this out using the Firefox "save complete web page" option on https://daringfireball.net/ and then running:

    shot-scraper /tmp/Daring\ Fireball.html --height 1200

Got this output (because I had run it a few times before so the filename had to change):

    Screenshot of 'file:/tmp/Daring Fireball.html' written to 'tmp-DaringFireball-html.2.png'

Result:

![tmp-DaringFireball-html 2](https://user-images.githubusercontent.com/9599/158070234-c32e6280-5a6a-4601-91b3-0f0f859a5289.png)

**Comment by pjamargh** [comment]
This is great. Thanks a ton, Simon!
