### ISSUE TITLE
Encountering timeout errors in GitHub Actions I don't see locally

### ISSUE THREAD

**Issue by palewire** [simonw/shot-scraper#46]
Here's [a recent call](https://github.com/palewire/news-homepages/runs/5621127998?check_suite_focus=true) that hung for 360 minutes before being killed by GitHub. I'm unclear of the cause.

**Comment by palewire** [comment]
I think this could be something besides a timeout. I added a shorter timeout method in #47 and then tried a site that's caused problems in interactive mode.

```
pipenv run shot-scraper shot https://ktla.com --timeout=10000 --interactive
```
The page loads. I  hit enter in the terminal to approve the screenshot. It still hangs.

![Screenshot from 2022-03-21 11-20-11](https://user-images.githubusercontent.com/9993/159338862-ac2f5994-24c7-4f29-85f1-bdb680ce1aa6.png)

My hunch is there must be some event in playwright that isn't firing. Not sure yet though. Any help would be appreciated.

**Comment by palewire** [comment]
Here's the console log from that site. It's a news site, so it's full of errors, of course.

[ktla.com-1647887063269.log](https://github.com/simonw/shot-scraper/files/8318306/ktla.com-1647887063269.log)

**Comment by palewire** [comment]
Here are the errors. 
![Screenshot from 2022-03-21 11-26-15](https://user-images.githubusercontent.com/9993/159339584-1c472db1-1ec1-41c0-87a2-e695f38c0ae4.png)

**Comment by palewire** [comment]
After adding some click.echo logs to the cli file and repeated testing, I'm fairly confident that the problem isn't with the page load but is instead somewhere inside the `page.screenshot()` method.

**Comment by palewire** [comment]
This may be related https://github.com/microsoft/playwright/issues/9757

**Comment by simonw** [comment]
I agree, having a default timeout feels like the right thing to do here. Can give people an option to turn that timeout off if they really don't want it for some reason.

**Comment by palewire** [comment]
Fun fact: I just downgraded to playwright version 14.1 as recommended in https://github.com/microsoft/playwright/issues/9757 and the site above worked immediately, after failing 10 times before.

**Comment by simonw** [comment]
To clarify, this bug occurs even with your new timeout mechanism from this PR?
- #47

**Comment by palewire** [comment]
Yes. It appears to be an issue deeper inside the screenshot method, after the page has finished loading.

**Comment by simonw** [comment]
Since this looks to be a Playwright bug I'm inclined not to work around it at a code level, but instead to describe a workaround in the documentation.

Have you tried setting a time limit on the GitHub Actions step that takes the screenshot? Something like this should be pretty reliable I would hope:

    timeout-minutes: 5

It looks like you started doing that four hours ago: https://github.com/palewire/news-homepages/commit/8be430047fa9045f028dfe8c7574484cbb7a1e73

**Comment by palewire** [comment]
Yep. Did that. And then downgraded my Playwright install as recommended in their issue tracker.

https://github.com/palewire/news-homepages/commit/033d42dfff81b249898a78d693ac75d2e4bb47f0

A job that had been hanging for days suddenly worked.

https://twitter.com/i/lists/1314593721069965312?s=20

Raises my confidence that's the root cause. Not sure if you want to pin your version or not. My bet would be this problem is caused by bad JS on badly engineeres sites, like the typical news site, and might not be that common.

On Mon, Mar 21, 2022, at 11:51 AM, Simon Willison wrote:
> 
> 
> Since this looks to be a Playwright bug I'm inclined not to work around it at a code level, but instead to describe a workaround in the documentation.
> 
> Have you tried setting a time limit on the GitHub Actions step that takes the screenshot? Something like this should be pretty reliable I would hope:
> 
> `timeout-minutes: 5
`

**Comment by palewire** [comment]
With the pinned version fixing the issue on my end, I am going to withdraw this issue. Thanks for your help.
