### ISSUE TITLE
Hanging issue with multi-shots

### ISSUE THREAD

**Issue by coding-to-music** [simonw/shot-scraper#48]
Cool project, thanks

I was able to get DrudgeReport and ZeroHedge, captured both

Then I added LA Times using the sample code provided in the readme, however it hung and needed to be killed (would have been 3 shots)

I rearranged the order and it would still hang after two shots

Removed the first two and it worked, getting 3 shots. But being able to get a long list of shots seems not consistent.

Not sure how to debug, but feel free to review any logs 
https://github.com/coding-to-music/page-snapshot-github-actions-shot-scraper/actions

**Comment by simonw** [comment]
Oh weird! Sounds like it might be the same issue reported in:
- #46

**Comment by simonw** [comment]
Try pinning to this version of Playwright and see if that fixes it: https://github.com/palewire/news-homepages/commit/033d42dfff81b249898a78d693ac75d2e4bb47f0

**Comment by coding-to-music** [comment]
I was thinking that too, looked similar

**Comment by coding-to-music** [comment]
I only see my requirements.txt which contains shot-scraper

I would need to build that with a pinned version? and reference it in requirements.txt, my own version?

**Comment by simonw** [comment]
No, you should be able to install that version by running this:

    pip install playwright==1.14.1

`shot-scraper` will then use that version instead.
