### ISSUE TITLE
--wait-for / wait_for mechanism for waiting until a JavaScript expression returns true

### ISSUE THREAD

**Issue by psychemedia** [simonw/shot-scraper#72]
The Playwright [`.wait_for_function()`](https://playwright.dev/python/docs/api/class-page#page-wait-for-function) allows you to wait for a certain condition to met before progressing to the next step.

It would be useful to support this sort of conditional delay when there is uncertainty about what an appropriate explicit `--wait` delay might be.

**Comment by simonw** [comment]
Interesting idea. It might be possible to support this as:

    shot-scraper datasette.io --wait-for-function "document.querySelector('iframe')"

Since it looks like `page.waitForFunction(...)` can accept a string instead of a function.

There's a default timeout of 30s. Not sure if it's worth having an extra `--wait-for-function-timeout` option which lets you change that default. I'm inclined to leave that off at first.

**Comment by simonw** [comment]
I like `--wait-for "..."` better. It's shorter.

**Comment by simonw** [comment]
Built a simple test page:

```html
<html>
<body><h1>Here it comes...</h1>
<script>
setTimeout(() => {
  var div = document.createElement('div');
  div.innerHTML = 'DIV after 2 seconds';
  document.body.appendChild(div);
}, 2000);
</script>
</body>
</html>
```
Used this for a prototype:

    shot-scraper div-after-2-seconds.html -o no-wait.png -w 300 -h 200

![no-wait](https://user-images.githubusercontent.com/9599/169416662-b5424b81-2145-4828-851a-b1259c4a2c05.png)

    shot-scraper div-after-2-seconds.html -o wait-for.png -w 300 -h 200 \
      --wait-for "document.querySelector('div')"

![wait-for](https://user-images.githubusercontent.com/9599/169416728-bcae7135-94ca-4342-b59e-333d68104be4.png)

Here's the prototype:

```diff
diff --git a/shot_scraper/cli.py b/shot_scraper/cli.py
index f2c96c6..3d238ae 100644
--- a/shot_scraper/cli.py
+++ b/shot_scraper/cli.py
@@ -117,6 +117,7 @@ def cli():
 @click.option(
     "--wait", type=int, help="Wait this many milliseconds before taking the screenshot"
 )
+@click.option("--wait-for", help="Wait until this JS expression returns true")
 @click.option(
     "--timeout",
     type=int,
@@ -151,6 +152,7 @@ def shot(
     retina,
     quality,
     wait,
+    wait_for,
     timeout,
     interactive,
     devtools,
@@ -198,6 +200,7 @@ def shot(
         "height": height,
         "quality": quality,
         "wait": wait,
+        "wait_for": wait_for,
         "timeout": timeout,
         "padding": padding,
         "retina": retina,
@@ -637,6 +640,7 @@ def take_shot(
         output = filename_for_url(url, ext="png", file_exists=os.path.exists)
     quality = shot.get("quality")
     wait = shot.get("wait")
+    wait_for = shot.get("wait_for")
     padding = shot.get("padding") or 0
 
     selectors = shot.get("selectors") or []
@@ -673,10 +677,14 @@ def take_shot(
 
     if wait:
         time.sleep(wait / 1000)
+
     javascript = shot.get("javascript")
     if javascript:
         _evaluate_js(page, javascript)
 
+    if wait_for:
+        page.wait_for_function(wait_for)
+
     screenshot_args = {}
     if quality:
         screenshot_args.update({"quality": quality, "type": "jpeg"})

```

**Comment by simonw** [comment]
I decided to evaluate any JavaScript from `--javascript` _before_ the `--wait-for` code is executed.

**Comment by simonw** [comment]
Documentation is now live here: https://shot-scraper.datasette.io/en/latest/screenshots.html#waiting-until-a-specific-condition
