### ISSUE TITLE
Furo documentation : the show source button

### ISSUE THREAD

**Issue by pvergain** [simonw/shot-scraper#78]
Hi,

This is an **informative issue** for the furo theme:  if you want the 'show source' button you have to use the furo (https://github.com/pradyunsg/furo/releases/tag/2022.01.02) release.

See:

- https://github.com/pradyunsg/furo/discussions/443
- https://github.com/pradyunsg/furo/discussions/374

Thank you Simon for for your fantastic work !

**Comment by simonw** [comment]
The build logs for https://shot-scraper.datasette.io/en/0.14.1/ on https://readthedocs.org/projects/shot-scraper/builds/17012547/ show that it used `furo-2022.4.7-py3-none-any.whl` 

In #82 I'm trying the most recent Furo release.

**Comment by simonw** [comment]
Oh, I think I see - I would need to set `html_show_sphinx = True` if I wanted to include that "Show source" link in my documentation.

Since the docs are available as raw markdown in GitHub I don't plan to add that setting.
