### ISSUE TITLE
How to send POST to url?

### ISSUE THREAD

**Issue by ZobaJakColbert** [simonw/shot-scraper#80]
Is there any option to add params to send post to url?

I need to send this key:value pair: `"data-raw": "page=21&limit=15"`

Or maybe with javascript there is a way to send POST to url?

I tried in javascript doing something like that, but no success:
```
--javascript "var xhr = new XMLHttpRequest(); xhr.open('POST', <url>, true); xhr.setRequestHeader('Content-Type', 'application/json'); xhr.send(JSON.stringify({'data-raw': 'page=21&limit=15'}));"
```

**Comment by simonw** [comment]
There isn't yet, but this seems like a good idea for a feature to me.

**Comment by simonw** [comment]
Thinking about how this could look, maybe something like this:

    shot-scraper http://www.example.com/ --post -f name value -f name2 value2

I don't think there's any need to support other verbs such as `OPTIONS` or `PUT` or `DELETE.

**Comment by simonw** [comment]
The YAML format for `shot-scraper multi` could look like this:

```yaml
- url: http://www.example.com/
  method: POST
  form:
    name value
    name2: value2

**Comment by simonw** [comment]
The YAML version could support additional methods too, since it would be using `method: X`.

**Comment by simonw** [comment]
This actually looks harder than I thought. The `page.goto(url)` method used here:

https://github.com/simonw/shot-scraper/blob/3fdb4a3d760bc316f6e4385e36daefa51873585d/shot_scraper/cli.py#L518-L523

Doesn't seem to have a mechanism for sending a POST instead of a GET: https://playwright.dev/docs/api/class-page#page-goto

**Comment by simonw** [comment]
Related challenge: most of the apps that I interact with have some form of CSRF protection - which means you often can't start by doing a POST directly to them, you instead need to load a previous page to set the CSRF cookie before making the form submission.

**Comment by simonw** [comment]
I think the best way to handle this today is with the existing `--javascript` option.

Here's an example which takes a screenshot of my blog's "you got the password wrong" screen:

```
shot-scraper 'https://simonwillison.net/admin/' --javascript '
document.getElementById("id_username").value = "username";
document.getElementById("id_password").value = "password";
document.getElementById("id_username").form.submit();' --wait 1000
Screenshot of 'https://simonwillison.net/admin/' written to 'simonwillison-net-admin.png'
```

![simonwillison-net-admin](https://user-images.githubusercontent.com/9599/181380051-d5515c43-5195-4bce-bb35-5216a9f4ec86.png)
